[versions]
kotlin = "2.3.20-Beta1"
shadow = "8.3.6"
kotlinx-coroutines = "1.9.0"
exposed = "0.46.0"
hikaricp = "5.1.0"
h2 = "2.2.224"
slf4j = "2.0.9"
jsr305 = "3.0.2"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }

[bundles]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc", "exposed-java-time"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
